apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: samgreend/spring-app:latest
        ports:
        - containerPort: 8111
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: SPRING_DATASOURCE_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: JWT_SECRET
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: MAIL_PASSWORD
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: GOOGLE_CLIENT_SECRET
        - name: KAKAO_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: KAKAO_CLIENT_SECRET
        - name: NAVER_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: NAVER_CLIENT_SECRET
        - name: NURIGO_API_KEY
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: NURIGO_API_KEY
        - name: NURIGO_API_SECRET
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: NURIGO_API_SECRET
        - name: NURIGO_SENDER
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: NURIGO_SENDER
        - name: CODEF_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: CODEF_CLIENT_ID
        - name: CODEF_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: spring-secret
              key: CODEF_SECRET_KEY
        - name: FLASK_BASE_URL
          value: "http://flask-service:5000"
