name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Spring image
        uses: docker/build-push-action@v5
        with:
          context: ./BackendCapstone
          push: true
          tags: samgreend/spring-app:latest

      - name: Build and Push Flask image
        uses: docker/build-push-action@v5
        with:
          context: ./flask_app
          push: true
          tags: samgreend/flask-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo chmod 644 /etc/rancher/k3s/k3s.yaml
            kubectl rollout restart deployment spring-deployment
            kubectl rollout restart deployment flask-deployment
            kubectl rollout status deployment spring-deployment
            kubectl rollout status deployment flask-deployment
